# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template that represents a task on Amazon ECS.
Parameters:
  TaskName:
    Type: String
  TaskCPU:
    Type: String
  TaskMemory:
    Type: String
  ContainerImage:
    Type: String
  LogRetention:
    Type: Number
    Default: 30
  TaskRole:
    Type: String
  Command:
    Type: String
  # TODO: env var needs to be a list of key-value pairs
  EnvVars:
    Type: String
Conditions:
  HasTaskRole:
    !Not [!Equals [!Ref TaskRole, ""]]
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: ECRRepo
    Properties:
      # TODO: Environment
      ContainerDefinitions:
        Image: !Ref ContainerImage
        Command: !Split [" ", !Ref Command]
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region: !Ref AWS::Region
            awslogs-group: !Ref LogGroup
            awslogs-stream-prefix: copilot-task
        Name: !Ref TaskName
      Family: !Join ['-', [!Ref TaskName]]
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: !Ref TaskCPU
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn:
        !If [HasTaskRole, !Ref TaskRole, !Ref "AWS::NoValue"]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["-", ["copilot", !Ref TaskName]]
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: "AllowPushPull"
            Effect: Allow
            Principal:
              Aws:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/*
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', ["/copilot/", !Ref TaskName]]
      RetentionInDays: !Ref LogRetention